name: movie_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  http: ^1.2.2
  auto_size_text: ^3.0.0
  html: ^0.15.5
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


flutter_native_splash :
  android : true
  ios: true
  web: false

  # color: "#bbdbed"
  # for android 11 and below
  background_image: "assets/moviez.png"
  image: "assets/logo.png"
  branding: "assets/brand.png"

  # for 12 or more
  android_12:
    background_image: "assets/moviez.png"
    image: "assets/logo.png"
    branding: "assets/brand.png"
